remote_theme: just-the-docs/just-the-docs
title: My homepage
description: Bookmark this to keep an eye on my project updates!

# Site settings
author: Bogdan Minko
email: minkobogdan2001@gmail.com
github_username: bogdan01m

# SEO улучшения
lang: en

# Соцсети (опционально)
social_links:
  github: https://github.com/bogdan01m
  linkedin: https://www.linkedin.com/in/bogdan-minko-05a867322/
  medium: https://medium.com/@minkobogdan2001
  habr: https://habr.com/ru/users/Bogdan_m01

# Just the Docs theme configuration
color_scheme: dark
search_enabled: true
heading_anchors: true

# Navigation structure
nav_order: 1