site_name: Bogdan Minko
site_description: AI/ML Engineer Portfolio
site_author: Bogdan Minko
site_url: https://bogdan01m.github.io

theme:
  name: material
  palette:
    # Scheme for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Scheme for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate

nav:
  - Home: index.md
  - About: about.md
  - Projects: projects.md
  - Contact: contact.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bogdan01m
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bogdan-minko-05a867322/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@minkobogdan2001